config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'media_items#index'
  resources :media_items, except: %i[show edit update]

  namespace :api do
    namespace :v1 do
      resources :media_items, only: [:index]
    end
  end
end

app/models/media_item.rb
require 'uri'

class MediaItem < ActiveRecord::Base
  belongs_to :user

  TYPES = %w[Website Video Image]

  validates :user,       presence:  true
  validates :name,       presence:  true
  validates :url,        presence:  true
  validates :is_private, inclusion: { in: [true, false] }
  validates :media_type, presence:  true, inclusion: { in: TYPES }

  validates_url :url, message: 'is invalid.'

  scope :public_items, -> { where(is_private: false) }
  scope :by_name, ->(name) { where('name LIKE ?', "%#{name}%") }

  def self.search(user, name)
    if user && name
      for_user(user).by_name(name)
    elsif user
      for_user(user)
    elsif name
      public_items.by_name(name)
    else
      public_items
    end
  end

  def self.for_user(user)
    order = sanitize_sql_array(["user_id = ? DESC, is_private DESC", user.id])
    where("is_private = ? OR user_id = ?", false, user).order(order)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :media_items, dependent: :destroy
end

app/controllers/api/v1/media_items_controller.rb
class Api::V1::MediaItemsController < ApplicationController
  respond_to :json

  def index
    items = MediaItem.search(current_user, params[:search])
    respond_with items
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/media_items_controller.rb
class MediaItemsController < ApplicationController
  before_action :authenticate_user!, except: :index

  respond_to :html

  def index
    @media_items = MediaItem.search(current_user, params[:search])
  end

  def new
    @media_item = current_user.media_items.build
  end

  def create
    @media_item = current_user.media_items.create(media_item_params)
    respond_with @media_item, location: media_items_path
  end

  def destroy
    @media_item = current_user.media_items.find(params[:id])
    @media_item.destroy
    respond_with @media_item, location: media_items_path
  end

  private

  def media_item_params
    params.require(:media_item).permit(:name, :url, :media_type, :is_private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
      'success' => 'alert-success',
      'error' => 'alert-danger',
      'alert' => 'alert-warning',
      'notice' => 'alert-info'
    }[flash_type]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MediaItemsCollection</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav role="navigation" class="navbar navbar-default">
    <div class="navbar-header">
        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="#" class="navbar-brand">Media Collection</a>
    </div>
    <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to 'Add Item', new_media_item_path %></li>
          <% end %>
          <li><%= link_to 'Item List', media_items_path %></li>
        </ul>

        <%= form_tag media_items_path, method: :get, class: "navbar-form navbar-left" do |f| %>
            <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
        <% end %>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: 'delete' %></li>
          <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>
        </ul>
    </div>
</nav>

<% flash.each do |type, message| %>
  <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
    </button>
    <%= message %>
  </div>
<% end %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/media_items/index.html.haml
%h2
  Media items:

%table.table#media_items
  %thead
    %th Link
    %th Type
    %th Private
    %th
  %tbody
    - @media_items.each do |item|
      %tr
        %td= link_to item.name, item.url
        %td= item.media_type
        %td= item.is_private?
        %td= item.user_id
        %td= link_to 'Delete', media_item_path(item), method: :delete, data: { confirm: 'Are you sure?' }

app/views/media_items/new.html.haml
%h2 New media item

.col-md-7
  = simple_form_for @media_item do |f|
    = f.input :name
    = f.input :media_type, label: "Media Type", collection: MediaItem::TYPES 
    = f.input :url
    = f.input :is_private, label: 'Private'
    = f.button :submit